//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQCare.Web.CCC.Screening {
    
    
    public partial class CervicalCancerScreening {
        
        /// <summary>
        /// CervicalCancerScreeningScreeningPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IQCare.Web.CCC.UC.Screening.ucCervicalCancerScreening CervicalCancerScreeningScreeningPanel;
    }
}
